View/Controllers/CategoriaController.cs
using Model;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class CategoriaController : Controller
    {
        private CategoriaRepository repository;

        public CategoriaController()
        {
            repository = new CategoriaRepository();
        }

        // GET: Categoria
        public ActionResult Index()
        {
            List<Categoria> categorias = repository.ObterTodos();
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        public ActionResult Store(string nome)
        {
            Categoria categoria = new Categoria();
            categoria.Nome = nome;
            repository.Inserir(categoria);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Categoria categoria = repository.ObterPeloId(id);
            ViewBag.Categoria = categoria;
            return View();
        }

        public ActionResult Update(int id, string nome)
        {
            Categoria categoria = new Categoria();
            categoria.Id = id;
            categoria.Nome = nome;
            repository.Alterar(categoria);
            return RedirectToAction("Index");
        }

    }
}

View/Controllers/PokemonController.cs
using Model;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class PokemonController : Controller
    {
        private PokemonRepository repositorio;

        public PokemonController()
        {
            repositorio = new PokemonRepository();
        }
        // GET: Pokemon
        public ActionResult Index()
        {
            List<Pokemon> pokemons = repositorio.ObterTodos("");
            ViewBag.Pokemons = pokemons;
            return View();
        }

        public ActionResult Cadastro()
        {
            CategoriaRepository categoriaRepository = new CategoriaRepository();
            List<Categoria> categorias = categoriaRepository.ObterTodos();
            ViewBag.Categorias = categorias;
            return View();

        }

        public ActionResult Store(int idCategoria, string nome)
        {
            Pokemon pokemon = new Pokemon();
            pokemon.IdCategoria = idCategoria;
            pokemon.Nome = nome;
            repositorio.Inserir(pokemon);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Pokemon pokemon = repositorio.ObterPeloId(id);
            ViewBag.Pokemon = pokemon;

            CategoriaRepository categoriaRepository = new CategoriaRepository();
            List<Categoria> categorias = categoriaRepository.ObterTodos();
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Update(int id, string nome, int idCategoria)
        {
            Pokemon pokemon = new Pokemon();
            pokemon.Id = id;
            pokemon.Nome = nome;
            pokemon.IdCategoria = idCategoria;
            repositorio.Alterar(pokemon);

            return RedirectToAction("Index");
        }
    }
}

View/Views/Categoria/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<h3>Cadastro de Categoria</h3>

<form action="@Url.Action("Store")" method="post">

    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="campo-nome">Nome</label>
                <input class="form-control" type="text" name="nome" id="campo-nome"/>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <button class="btn btn-success float-right" type="submit"><i class="fas fa-save"></i> Salvar</button>
        </div>
    </div>
</form>

View/Views/Categoria/Editar.cshtml
@{
    ViewBag.Title = "Editar";
}

<h3>Editar Categoria</h3>

<form action="@Url.Action("Update")" method="post">
    <input type="hidden" name="id" value="@ViewBag.Categoria.Id" />
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="campo-nome">Nome</label>
                <input type="text" name="nome" class="form-control" id="campo-nome" value="@ViewBag.Categoria.Nome" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-success float-right">
                <i class="fas fa-save"></i> Salvar
            </button>
        </div>
    </div>
</form>

View/Views/Categoria/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3 class="text-center">Lista de Categorias</h3>
<div class="row">
    <div class="col-10 offset-1 mb-3">
        <a class="btn btn-primary float-right" href="@Url.Action("Cadastro")">
        <i class="fa fa-plus"></i> Nova Categoria</a>
    </div>
</div>

<div class="row">
    <div class="col-10 offset-1">

        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Model.Categoria categoria in ViewBag.Categorias)
                {
                    <tr>
                        <td>@categoria.Id</td>
                        <td>@categoria.Nome</td>
                        <td>
                            <a href="@Url.Action("Editar", new { Id = categoria.Id })" class="btn btn-primary">
                                <i class="fas fa-pen"></i> Editar
                            </a>

                            <a href="@Url.Action("Apagar", new { Id = categoria.Id })" class="btn btn-danger">
                                <i class="fas fa-trash"></i> Apagar
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Ação</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

View/Views/Pokemon/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<h3>Cadastro de Pokemon</h3>

<form action="@Url.Action("Store")" method="post">
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="campo-categoria">Categoria</label>
                <select id="campo-categoria" name="idCategoria" class="form-control">
                    <option disabled="disabled" selected="selected">Selecione uma categoria</option>
                    @foreach(Model.Categoria categoria in ViewBag.Categorias)
                    {
                        <option value="@categoria.Id">@categoria.Nome</option>
                    }
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="campo-nome">Nome</label>
                <input type="text" name="nome" id="campo-nome" class="form-control"/>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <button class="btn btn-success float-right">
                <i class="fas fa-save"></i> Salvar
            </button>
        </div>
    </div>
</form>

View/Views/Pokemon/Editar.cshtml
@{
    ViewBag.Title = "Editar";
}

<h3>Editar Pokemon</h3>

<form action="@Url.Action("Update")" method="POST">
    <input type="hidden" name="id" value="@ViewBag.Pokemon.Id" />

    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="campo-categoria">Categoria</label>
                <select id="campo-categoria" name="idCategoria" class="form-control">
                    @foreach(Model.Categoria categoria in ViewBag.Categorias)
                    {
                        if(categoria.Id == ViewBag.Pokemon.IdCategoria)
	                    {
		                    <option value="@categoria.Id" selected="selected">@categoria.Nome</option>
                        }
                        else
                        {
                            <option value="@categoria.Id">@categoria.Nome</option>
                        }
                    }

                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="campo-nome">Nome</label>
                <input type="text" name="nome" id="campo-nome" value="@ViewBag.Pokemon.Nome" class="form-control"/>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <button class="btn btn-success" type="submit"><i class="fas fa-save"></i> Salvar</button>
        </div>
    </div>

</form>

View/Views/Pokemon/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>Lista de Pokemons</h3>

<div class="row">
    <div class="col-12">
        <a class="btn btn-primary float-right" href="@Url.Action("Cadastro")">Novo Pokemon</a>
    </div>
</div>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Código</th>
            <th>Categoria</th>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th>Código</th>
            <th>Categoria</th>
            <th>Nome</th>
            <th>Ação</th>
        </tr>

        <tbody>
            @foreach(Model.Pokemon pokemon in ViewBag.Pokemons)
            {
                <tr>
                    <td>@pokemon.Id</td>
                    <td>@pokemon.Categoria.Nome</td>
                    <td>@pokemon.Nome</td>
                    <td>
                        <a href="@Url.Action("Editar", new {id = pokemon.Id})" class="btn btn-primary"><i class="fas fa-pen"></i> Edita</a>

                        <a href="@Url.Action("Apagar", new { id = pokemon.Id })" class="btn btn-danger"><i class="fas fa-trash"></i> Apagar</a>

                    </td>
                </tr>
            }
        </tbody>

    </tfoot>
</table> 

View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" type="text/css"/>
    <link rel="icon" href="~/Content/bug.ico"/>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">POKEDEX</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" 
                       href="@Url.Action("Index", "Categoria")">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Pokemon")" >Pokemons</a>
                </li>

            </ul>
        </div>
    </nav>

    <div class="container-fluid mt-3">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>